### ISSUE TITLE
Getting blake3_dotnet.dll missing error

### ISSUE THREAD

**Issue by niyas9231** [xoofx/Blake3.NET#19] opened 2023-05-29 16:48 UTC
Hi,

I have installed the latest Blake3.NET package 0.5.1 in my application. But while running the code, getting an error like blake3_dotnet.dll is missing. Could you please help me on this issue?

Thanks,
Niyas

**Comment by alexmurari** [comment] 2023-07-21 20:16
Probably a duplicate of https://github.com/xoofx/Blake3.NET/issues/15

**Closed as completed** 2023-07-23 17:00 UTC
Labels: duplicate
